version: "3.9"
services:
  eventhub:
    build: .
    command: flask run --host 0.0.0.0 --port 5000
    environment:
      FLASK_APP: eventhub
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
