version: "3.9"
services:
  eventhub:
    build: .
    command: flask run --host 0.0.0.0 --port 8000
    environment:
      FLASK_APP: eventhub
      FLASK_ENV: development
      LOGLEVEL: INFO
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
